Adding StringUtils class and test file.
Anshika1603/JUnitAssignment pull request #1
Opened 2023-04-08 11:32 UTC by Anshika1603

Please review and allow me to merge JUnit4 Assignment.

2023-04-09 13:05 UTC, anup0060 requested changes

2023-04-09 13:05 UTC, anup0060 commented on src/main/java/StringUtils.java
> +        else {
if first if returning , then no need to have else.

2023-04-09 13:05 UTC, anup0060 commented on src/main/java/StringUtils.java
> +        Scanner Input=new Scanner(System.in);
poor variable naming .

2023-04-09 13:05 UTC, anup0060 commented on src/main/java/StringUtils.java
> +        String UserInput=Input.nextLine(); // Taking input from user
use camel casing for variables

2023-04-09 13:05 UTC, anup0060 commented on src/test/java/StringUtilsTest.java
> +    public void testReverse_shouldReturn_String(){
you also need to mention given. means when should is expected. 

testReverse_shouldReturnString_givenExpectedInput

2023-04-11 13:16 UTC, Anshika1603 commented
I have worked on the changes and updated the classes. Please review it.

2023-04-12 14:11 UTC, anup0060 requested changes

2023-04-12 14:11 UTC, anup0060 commented on src/test/java/StringOperationsTest.java
> +    public void testIsEmpty_shouldReturnBoolean_givenString(){
empty case should be separate (we can have case for true and other for false)

2023-04-12 14:11 UTC, anup0060 commented on src/test/java/StringOperationsTest.java
> +        assertFalse(stringOperations.isPalindrome(""));
empty case separate

2023-04-12 14:11 UTC, anup0060 commented on src/main/java/StringOperations.java
> +    public String reverse(String inputStatement){
variable name inputStatement not good. you can say - inputStr

2023-04-12 17:06 UTC, Anshika1603 commented
I have added different test methods for empty cases and also changed the variable name. Please review.

2023-04-12 17:30 UTC, anup0060 approved these changes

2023-04-12 17:30 UTC, merged